docker image

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -16,25 +16,44 @@ env:
   REGISTRY: docker.io
   # Image repository, without hostname and tag
   IMAGE_NAME: alpine/minio
+  REPO_NAME: minio/minio
+  REBUILD: false
   SHA: ${{ github.event.pull_request.head.sha || github.event.after }}
 
 jobs:
-  build:
+  check_tag:
     runs-on: ubuntu-latest
+    permissions:
+      pull-requests: write
+
+    steps:
+      # Step to fetch the latest version
+      - name: Get latest version
+        id: curl-version
+        run: |
+           VERSION=$(curl -s https://api.github.com/repos/${REPO_NAME}/releases | jq -r '.[].tag_name | select(test("alpha|beta|rc") | not) ' | sort -rV | head -n 1 |sed 's/v//')
+           echo "Latest release is $VERSION"
+           echo "VERSION=$VERSION" >> $GITHUB_ENV
+           status=$(curl -sL https://hub.docker.com/v2/repositories/${IMAGE_NAME}/tags/${VERSION})
+           echo $status
+           if [[ ( "${status}" =~ "not found" ) ||( ${REBUILD} == "true" ) ]]; then
+             echo "build image for ${VERSION}"
+             echo "build_required=true" >> $GITHUB_OUTPUT
+           else
+             echo "Tag is exist, skip"
+             echo "build_required=false" >> $GITHUB_OUTPUT
+           fi
+
+  build_and_push:
+    runs-on: ubuntu-latest
+    needs: check_tag
+    if: needs.check_tag.outputs.build_required == 'true'
     permissions:
       pull-requests: write
 
     steps:
       - name: Setup Docker buildx
         uses: docker/setup-buildx-action@v3
-
-      # Step to fetch the latest version
-      - name: Get latest version
-        id: curl-version
-        run: |
-           VERSION=$(curl -s https://api.github.com/repos/minio/minio/releases | jq -r '.[].tag_name | select(test("alpha|beta|rc") | not) ' | sort -rV | head -n 1 |sed 's/v//')
-           echo "Latest minio version is $VERSION"
-           echo "VERSION=$VERSION" >> $GITHUB_ENV
 
       # Authenticate to the container registry
       - name: Authenticate to registry ${{ env.REGISTRY }}
@@ -88,7 +107,7 @@ jobs:
           # docker_version=$(echo ${docker_version}| awk -F \" '{print $2}' |sed 's/v//')
 
           # Get the latest releases tag, excludes alpha, beta, rc tags
-          release=$(curl -s https://api.github.com/repos/minio/minio/releases | jq -r '.[].tag_name | select(test("alpha|beta|rc") | not) ' \
+          release=$(curl -s https://api.github.com/repos/${REPO_NAME}/releases | jq -r '.[].tag_name | select(test("alpha|beta|rc") | not) ' \
                | sort -rV | head -n 1 |sed 's/v//')
 
           echo $release
